'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Checkmate.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic_mainScreenChessboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_mainScreenChessboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic_timeControlInfoExample() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_timeControlInfoExample", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RNBQKBNRPPPPPPPP                                pppppppprnbqkbnr.
        '''</summary>
        Friend ReadOnly Property txt_chessboardStartingPosition() As String
            Get
                Return ResourceManager.GetString("txt_chessboardStartingPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time controls restrict the total time each player has in a game. The time a player takes on their turn is deducted from the time they have remaining while the other players clock is paused. Once a player moves, their clock is paused while the other player takes their turn..
        '''</summary>
        Friend ReadOnly Property txt_timeControlInfoLabel1() As String
            Get
                Return ResourceManager.GetString("txt_timeControlInfoLabel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As well as total time controls, there is also something known as &apos;increment&apos;. Increment is a certain amount of time that is added onto each player&apos;s time once their turn is started. For example, if a game was started with a two minute time control and a fifteen second increment and the first player took five seconds to move, they would have two minutes - five seconds + fifteen seconds increment = two minutes and five seconds left on their clock..
        '''</summary>
        Friend ReadOnly Property txt_timeControlInfoLabel2() As String
            Get
                Return ResourceManager.GetString("txt_timeControlInfoLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time controls are expressed as x+y, where x is the total time in minutes for each player and y is the increment in seconds. E.g a &apos;1 + 5&apos; game would mean each player has one minute to play and five seconds increment..
        '''</summary>
        Friend ReadOnly Property txt_timeControlInfoLabel3() As String
            Get
                Return ResourceManager.GetString("txt_timeControlInfoLabel3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
